### ISSUE TITLE
equally spaced

### ISSUE THREAD

**Issue by adammaj1** [ekatrukha/ContourLines#1]
Hi. 
Your contour lines are equally spaced. 
I use similar IMHO [technique - level set method](https://en.wikipedia.org/wiki/Level-set_method) and edge detection. 
Here is [example with src code ](https://commons.wikimedia.org/wiki/File:Julia_set_for_z%5E2%2B0.7i*z.png)
 In my image boundary  itself is not drawn: we see it as the locus of points where the level curves are especially close to each other = a place with high density of level curves. 
I do knot know if it is important for you. If yes you can use gray leve to change distance between contour lines. 

Second thing : I try to udjust images that level curves cross at critical point, here [saddle point](https://en.wikipedia.org/wiki/Saddle_point)

Here is [more description](https://en.wikibooks.org/wiki/Fractals/Iterations_in_the_complex_plane/Julia_set#Internal_Level_Sets)

What do you think about it ?

**Comment by ekatrukha** [comment]
Hi Adam,

It is intentionally made to produce equally spaced lines. 
I think there is already ImageJ plugin that generates kind of "level set" curves, see [Contour plotter](https://imagej.nih.gov/ij/plugins/contour-plotter.html)
I guess both methods have their shortcomings and advantages.

In the level step method, I guess, you need to come up with an algorithm that would optimally sample intensity levels (level sets), so that final set of curves reflects and illustrates corresponding changes of the surface shape. I think for general case it is not a trivial task and more of trial and error.
On the other hand it is very informative: the density of the curves reflect the "steepness" of intensity/surface. 
But, again, if there are some local peculiarities in the area with low curve densities, this method will not show them, since the curves density is low there by design.  
The "equally spaced" contour lines will be able to overcome it, since they basically sample the area the image/surface equidistantly. But this method loses its illustrative aspect, since now the density of curves does not reflect "steepness". I.e. level sets are sampled non-linearly.
 
In the end, I think, it is good to have both methods and choose one that is best for specific task/problem at hand.

Cheers,
Eugene
